### ISSUE TITLE
Error running with today version.

### ISSUE THREAD

**Issue by landjea** [remoblaser/laravel-resourceful#8]
Installed a fresh L5, added your bit and it is complaining about no service provider

```
 [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'Remoblaser\Resourceful\ResourcefulServiceProvider' not found
```

**Comment by remoblaser** [comment]
Will have a look at it in about 10 minutes

**Comment by remoblaser** [comment]
Alright, i was using psr-0 which caused the error. I've fixed it here 32b03d4518e75d074495a11c5a552346fd9f0f6c. Remove the ServiceProvider, make a composer update and add the ServiceProvider again, then it should work.

Thanks for the issue!

**Comment by landjea** [comment]
Ahhh. I was poking around your service provider and I couldn't see anything
amiss with your namespace or paths...thanks!

**Comment by remoblaser** [comment]
Was doing the same until i checked the autoload files and was like "duh, i'm a idiot", glad if it works for you now!

**Comment by landjea** [comment]
Yeah, it's all good now. Thanks again.
